<?php

namespace Database\Seeders;

use App\Models\ApplicantQuestion;
use App\Models\User;
use Illuminate\Database\Seeder;

class ApplicantQuestionSeeder extends Seeder
{
    public function run(): void
    {
        ApplicantQuestion::create([
            'user_id' => User::where('email','press-user1@protonmail.com')->first()->id,
            'consanguinity_third' => 0,
            'consanguinity_fourth' => 'N/A',
            'consanguinity_details' => 'N/A',
            'admin_offense' => 0,
            'admin_offense_details' => 'N/A',
            'criminal_court' => 0,
            'criminal_court_details' => 'N/A',
            'criminal_court_filed' => 'N/A',
            'criminal_court_status' => 'N/A',
            'convicted_crime' => 0,
            'convicted_crime_details' => 'N/A',
            'service_separated' => 1,
            'service_separated_details' => 'N/A',
            'candidate' => 0,
            'candidate_details' => 'N/A',
            'campaign' => 0,
            'campaign_details' => 'N/A',
            'immigrant' => 0,
            'immigrant_details' => 'N/A',
            'ip' => 0,
            'ip_details' => 'N/A',
            'pwd' => 0,
            'pwd_details' => 'N/A',
            'solo_parent' => 0,
            'solo_parent_details' => 'N/A',
            'reference1_name' => 'A',
            'reference1_address' => 'A1',
            'reference1_contact_no' => '1',
            'reference2_name' => 'B',
            'reference2_address' => 'B2',
            'reference2_contact_no' => '2',
            'reference3_name' => 'C',
            'reference3_address' => 'C3',
            'reference3_contact_no' => '3',
            'govt_id' => 'Passport',
            'govt_id_no' => 'FIUAHF321R',
            'govt_id_issuance' => 'DVO/Oct 1 2024',
            'application_id' => 1,
            'is_latest' => 0,
            'version' => 1,
        ]);

        ApplicantQuestion::create([
            'user_id' => User::where('email','press-user2@proton.me')->first()->id,
            'consanguinity_third' => 0,
            'consanguinity_fourth' => 'N/A',
            'consanguinity_details' => 'N/A',
            'admin_offense' => 0,
            'admin_offense_details' => 'N/A',
            'criminal_court' => 0,
            'criminal_court_details' => 'N/A',
            'criminal_court_filed' => 'N/A',
            'criminal_court_status' => 'N/A',
            'convicted_crime' => 0,
            'convicted_crime_details' => 'N/A',
            'service_separated' => 1,
            'service_separated_details' => 'N/A',
            'candidate' => 0,
            'candidate_details' => 'N/A',
            'campaign' => 0,
            'campaign_details' => 'N/A',
            'immigrant' => 0,
            'immigrant_details' => 'N/A',
            'ip' => 0,
            'ip_details' => 'N/A',
            'pwd' => 0,
            'pwd_details' => 'N/A',
            'solo_parent' => 0,
            'solo_parent_details' => 'N/A',
            'reference1_name' => 'X',
            'reference1_address' => 'X1',
            'reference1_contact_no' => '1',
            'reference2_name' => 'Y',
            'reference2_address' => 'Y2',
            'reference2_contact_no' => '2',
            'reference3_name' => 'Z',
            'reference3_address' => 'Z3',
            'reference3_contact_no' => 'Z',
            'govt_id' => 'PRC',
            'govt_id_no' => '09523-GALEF',
            'govt_id_issuance' => 'MNL/Jan 1 2017',
            'application_id' => 1,
            'is_latest' => 0,
            'version' => 1,
        ]);

        // latest version
        
        ApplicantQuestion::create([
            'user_id' => User::where('email','press-user1@protonmail.com')->first()->id,
            'consanguinity_third' => 0,
            'consanguinity_fourth' => 'N/A',
            'consanguinity_details' => 'N/A',
            'admin_offense' => 0,
            'admin_offense_details' => 'N/A',
            'criminal_court' => 0,
            'criminal_court_details' => 'N/A',
            'criminal_court_filed' => 'N/A',
            'criminal_court_status' => 'N/A',
            'convicted_crime' => 0,
            'convicted_crime_details' => 'N/A',
            'service_separated' => 1,
            'service_separated_details' => 'Resignation',
            'candidate' => 0,
            'candidate_details' => 'N/A',
            'campaign' => 0,
            'campaign_details' => 'N/A',
            'immigrant' => 0,
            'immigrant_details' => 'N/A',
            'ip' => 0,
            'ip_details' => 'N/A',
            'pwd' => 0,
            'pwd_details' => 'N/A',
            'solo_parent' => 0,
            'solo_parent_details' => 'N/A',
            'reference1_name' => 'A',
            'reference1_address' => 'A1',
            'reference1_contact_no' => '1',
            'reference2_name' => 'B',
            'reference2_address' => 'B2',
            'reference2_contact_no' => '2',
            'reference3_name' => 'C',
            'reference3_address' => 'C3',
            'reference3_contact_no' => '3',
            'govt_id' => 'Passport',
            'govt_id_no' => 'FIUAHF321R',
            'govt_id_issuance' => 'DVO/Oct 1 2024',
            'application_id' => null,
            'is_latest' => 1,
            'version' => 2,
        ]);

        ApplicantQuestion::create([
            'user_id' => User::where('email','press-user2@proton.me')->first()->id,
            'consanguinity_third' => 0,
            'consanguinity_fourth' => 'N/A',
            'consanguinity_details' => 'N/A',
            'admin_offense' => 0,
            'admin_offense_details' => 'N/A',
            'criminal_court' => 0,
            'criminal_court_details' => 'N/A',
            'criminal_court_filed' => 'N/A',
            'criminal_court_status' => 'N/A',
            'convicted_crime' => 0,
            'convicted_crime_details' => 'N/A',
            'service_separated' => 1,
            'service_separated_details' => 'N/A',
            'candidate' => 0,
            'candidate_details' => 'N/A',
            'campaign' => 0,
            'campaign_details' => 'N/A',
            'immigrant' => 0,
            'immigrant_details' => 'N/A',
            'ip' => 0,
            'ip_details' => 'N/A',
            'pwd' => 0,
            'pwd_details' => 'N/A',
            'solo_parent' => 0,
            'solo_parent_details' => 'N/A',
            'reference1_name' => 'X',
            'reference1_address' => 'X1',
            'reference1_contact_no' => '1',
            'reference2_name' => 'Y',
            'reference2_address' => 'Y2',
            'reference2_contact_no' => '2',
            'reference3_name' => 'Z',
            'reference3_address' => 'Z3',
            'reference3_contact_no' => 'Z',
            'govt_id' => 'PRC',
            'govt_id_no' => '30935-GRSG8',
            'govt_id_issuance' => 'MNL/Jan 1 2024',
            'application_id' => null,
            'is_latest' => 1,
            'version' => 2,
        ]);

    }
}
